export { getAll };

var getAll = function() {
    return {
        "intro": "Outside the large front windows, the snow is falling down onto the cobbled street. You sigh when pondering all the lucky people preparing for Christmas and spending time with their loved ones...<br>...while you spend your time here. Alone in a bookshop that hasn't made a profit for years. You haven't had a vacation in a long time and with the current income flow, you are unlikely to get one anytime soon. Money is running out quickly, and if you don't do anything, the next Christmas the family's old shop will no longer be around.<br>You do not want to be the person that lost it.",

        "ghosts": "You remember the older people of your family, uncle Ailbert among them, talking about the old basement. In Victorian times, when the shop sold not only books, it was used for storage. During some time people also made their living down there - a seamstress and a dressmaker worked there for a while, as did a watchmaker.<br>Legend has it that at one point, two young lovers were locked inside, never to be seen again, and that their ghosts still exist somewhere down there.<br>The basement was locked up well before you were born, and you are probably the first person still alive to see it.",

        "dance": "You have no idea how, but suddenly soft music fills the air. You enter in an embrace with the semi-transparent man who encourages you along. It is a strange sensation, to be locked in an embrace with a character neither living nor dead, whose firm grip, while seemingly non-existent, at the same time is very firm. As you start dancing, you wonder whether you will actually be able to get out of his grip, should you want to do so.<br>He dances well, and you feel a strange joy flow through you. After a while, he slowly guides you of the room and you realize that he wants to continue dancing in the outer room, where there is more space.<br>As you enter the outer room, the female ghost looks at you with a strange expression on her face before she floats through one of the walls and disappears.<br>\"She is afraid of ghosts - how ironic\", the dancer states laconically. You dance for a while before he releases his grip, thanks you with a bow of his head and floats back into his room.",

        "won": "You enter a small room, about two meters square. The room is empty, apart from a small table in its center. On the table is a large book which you hesitantly pick up. As you start looking through the book, you realise that you have likely stumbled upon something unique. It appears to be an account of the fair city of \"Parswicke\", describing its origins, the cathedral, how its merchant guild is organized and an account of the notable people living in it. You cannot be certain, but the book gives you a Shakespearean feel. Could it be that old?",

        "later": "                                     ...one year later...",

        "festive": "Outside the large front windows, the snow is falling down onto the cobbled street. You think back, reflecting on the previous winter. Imagine... a year ago you expected to go bancrupt and have to abandon the old bookshop. Now however...<br>You turn away from the window and look out over the room. It is packed with people, some of whom are reverently admiring the old book that is now on display in a large glass cabinet along the opposite wall. Most of the visitors, however, are looking in the shelves for interesting Christmas gifts, some are having tea and scones at the tables, and further some are in line, waiting to order something from Eve and Joanna who are busy behind the counter.<br>You look at the portrait of your parents that now hangs next to the front door. You feel happy knowing that the old bookshop is again a thriving, vital part of Parswick's everyday life.<br><br>",

        "congrats": "                              Congratulations! You have won!",
    }
}