export { Flag };

const Flag = {
    WALL_BROKEN: 1,
    ENTRANCE_KNOWN: 2,
    UNCLE_AILBERT_INTRODUCED: 3,
    UNCLE_AILBERT_IN_BATHROOM: 4,
    UNCLE_AILBERT_HAS_LEFT: 5,
    MAKE_TEA_POSSIBLE: 6,
    BOOKSHELF_PULLED: 7,
    BOOKSHELF_EMPTY: 8,
    NEED_LIGHT_SOURCE: 9,
    GHOSTS_HAVE_BEEN_DESCRIBED: 10,
    NEED_DANCE_BOOK: 11,
    HAVE_READ_DANCE_BOOK: 12,
    NEEDS_TO_PRACTICE_DANCING: 13,
    HAVE_BEEN_STOPPED_BY_TOURISTS: 14,
    CAN_DANCE: 15,
};
